repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: elisp-lint
        name: elisp-lint
        entry: make all
        language: system
        always_run: true
        pass_filenames: false
